pull_request_rules:
  - name: automatic merge for PyUp pull requests
    conditions:
      - author=imgbot[bot]
      - status-success=Circle CI - Pull Request
    actions:
      merge:
        method: merge
