clone_depth: 5

environment:
    access_token:
        secure: Mf6FoZ1Z7hOB0Kg+ILKrUSmtF1v0j0xobM7duH+9BhOCo2psn/aPqdsm+zW1mmyG
install:
    - apt-get install curl
    - curl -sL https://deb.nodesource.com/setup_12.x | bash -
    - apt-get install -y nodejs
    - sudo apt-get -y install software-properties-common
    - sudo add-apt-repository -y ppa:rwky/graphicsmagick
    - sudo add-apt-repository -y ppa:mc3man/trusty-media
    - sudo apt-get -y update
    - sudo apt-get install -y libimage-exiftool-perl
    - sudo apt-get -y install python-software-properties
    - sudo apt-get -y install software-properties-common
    - sudo apt-get -y install ffmpeg
    - sudo apt-get -y install graphicsmagick
    - sudo apt-get -y install gifsicle
    - npm install -g thumbsup
build_script:
    - thumbsup --config config.json
    
artifacts:
    - path: build_output
    
on_success:
    - git config --global credential.helper store
    - ps: Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:access_token):x-oauth-basic@github.com`n"
    - git config --global user.email "%GIT_USER_EMAIL%"
    - git config --global user.name "%GIT_USER_NAME%"
    - git clone --depth 5 -q --branch=%TARGET_BRANCH% %STATIC_SITE_REPO% %TEMP%\static-site
    - cd %TEMP%\static-site
    - del * /f /q
    - for /d %%p IN (*) do rmdir "%%p" /s /q
    - SETLOCAL EnableDelayedExpansion & robocopy "%APPVEYOR_BUILD_FOLDER%\public" "%TEMP%\static-site" /e & IF !ERRORLEVEL! EQU 1 (exit 0) ELSE (IF !ERRORLEVEL! EQU 3 (exit 0) ELSE (exit 1))
    - git add -A
    - git commit -m "Update Static Site"
    - git push origin %TARGET_BRANCH%
    - appveyor AddMessage "Static Site Updated"
