version: 2
jobs:
  build:
    machine: true
    # The secondary container is an instance of the second listed image which is run in a common network where ports exposed on the primary container are available on localhost.
    steps:
      - add_ssh_keys:
          fingerprints: '62:35:25:b8:bb:39:ef:10:db:b7:5e:75:c4:c5:cd:f8'
      - checkout
      - run:
          name: Install Docker
          command: |
            pwd
            ls
            docker pull thumbsupgallery/thumbsup
            docker run -t -v `pwd`:/work -u $(id -u):$(id -g) thumbsupgallery/thumbsup sh -c "ls && cd work && ls && pwd && thumbsup --config config.json"
      - run: # git push
          name: push-github
          command: |
            sudo npm install -g --silent gh-pages@2.0.1
            git config --global user.email "24516641+TGYZ1909@users.noreply.github.com"
            git config --global user.name "TGYZ1909"
            gh-pages --dotfiles --message "[skip ci] Updates" --dist ./build_output

