version: 2
jobs:
  build:
    docker: # executor type
      - image: thumbsupgallery/thumbsup
    # The secondary container is an instance of the second listed image which is run in a common network where ports exposed on the primary container are available on localhost.
    steps:
      - add_ssh_keys:
          fingerprints: '62:35:25:b8:bb:39:ef:10:db:b7:5e:75:c4:c5:cd:f8'
      - checkout
      - run:
          name: Build
          command: |
            pwd
            ls
            thumbsup --config config.json
      - run: # git push
          name: push-github
          command: |
            sudo apt-get install git
            #sudo npm install -g --silent gh-pages@2.0.1
            git config --global user.email "24516641+TGYZ1909@users.noreply.github.com"
            git config --global user.name "TGYZ1909"
            #gh-pages --dotfiles --message "[skip ci] Updates" --dist ./build_output
            ls
            git add build_output && git commit -m "[skip ci] updates"
            git subtree push --prefix build_output origin gh-pages
