version: 2.1 # use CircleCI 2.1
jobs: # a collection of steps
  build: # runs not using Workflows must have a `build` job as entry point
    docker: # run the steps with Docker
      - image: circleci/node:10.16.3 # ...with this image as the primary container; this is where all `steps` will run
      - image: mongo:4.2.0 # and this image as the secondary service container
    steps: # a collection of executable commands
      - checkout # special step to check out source code to working directory
      - run:
          name: install dependence
          command: |
          sudo add-apt-repository -y ppa:rwky/graphicsmagick
          sudo add-apt-repository -y ppa:mc3man/trusty-media
          sudo apt-get -y update
          sudo apt-get install -y libimage-exiftool-perl
          sudo apt-get -y install python-software-properties
          sudo apt-get -y install software-properties-common
          sudo apt-get -y install ffmpeg
          sudo apt-get -y install graphicsmagick
          sudo apt-get -y install gifsicle
          npm install -g thumbsup
      - run:
          name: run thumbups
          command: |
          thumbsup --config config.json
