version: 2
jobs:
  build:
    working_directory: ~/mern-starter
    # The primary container is an instance of the first image listed. The job's commands run in this container.
    docker: # executor type
      - image: buildpack-deps:trusty
    # The secondary container is an instance of the second listed image which is run in a common network where ports exposed on the primary container are available on localhost.
    steps:
      - checkout
      - run:
          name: Update npm
          command: 'sudo apt-get update'
          command: 'sudo apt-get upgrade'
          command: 'sudo apt-get install curl'
          command: 'curl -sL https://deb.nodesource.com/setup_12.x | bash -'
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install Dependence
          command: 'sudo add-apt-repository -y ppa:rwky/graphicsmagick'
      - run:
          name: Install npm wee
          command: npm install
