version: 2
jobs:
  build:
    docker: # executor type
      - image: buildpack-deps:trusty
    # The secondary container is an instance of the second listed image which is run in a common network where ports exposed on the primary container are available on localhost.
    steps:
      - setup_remote_docker
      - add_ssh_keys:
          fingerprints: '62:35:25:b8:bb:39:ef:10:db:b7:5e:75:c4:c5:cd:f8'
      - checkout
      - run:
          name: Install docker
          command: |
            apt-get update --fix-missing
            apt-get install -y apt-transport-https ca-certificates software-properties-common
            curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
            apt-key fingerprint 0EBFCD88
            add-apt-repository \
              "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
              $(lsb_release -cs) \
              stable"
            apt-get update
            apt-get install -y docker-ce
            docker --version
      - run:
          name: Install Docker
          command: |
            docker pull thumbsupgallery/thumbsup
            docker run -t -v /root/project/:/work -u $(id -u):$(id -g) thumbsupgallery/thumbsup sh -c "cd work && thumbsup --config config.json"
      - run: # git push
          name: push-github
          command: |
            sudo npm install -g --silent gh-pages@2.0.1
            git config --global user.email "24516641+TGYZ1909@users.noreply.github.com"
            git config --global user.name "TGYZ1909"
            gh-pages --dotfiles --message "[skip ci] Updates" --dist ./build_output

